version: '3.8'

services:
  # THEA Backend Service
  thea-backend:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql:3306/thea_db
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - mysql
      - redis
      - minio
      - rabbitmq
    networks:
      - thea-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=thea_db
      - MYSQL_USER=thea_user
      - MYSQL_PASSWORD=thea_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./prisma/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - thea-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - thea-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - thea-network
    restart: unless-stopped
    command: server /data --console-address ":9001"

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - thea-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  minio_data:
  rabbitmq_data:

networks:
  thea-network:
    driver: bridge
